#!/usr/bin/env bash
set -u

resolve_project_dir() {
  if [ -n "${CLAUDE_PROJECT_DIR:-}" ] && [ -d "$CLAUDE_PROJECT_DIR" ]; then
    printf '%s\n' "$CLAUDE_PROJECT_DIR"
    return
  fi

  local script_dir
  script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
  CDPATH= cd -- "$script_dir/../.." && pwd
}

INPUT=$(cat)
FILE_PATH=$(
  printf '%s' "$INPUT" |
    sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' |
    head -n 1
)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

PROJECT_DIR=$(resolve_project_dir)

case "$FILE_PATH" in
  "$PROJECT_DIR"/*) ;;
  *) exit 0 ;;
esac

REL_PATH="${FILE_PATH#$PROJECT_DIR/}"

IS_GENERATED=0
case "$REL_PATH" in
  AGENTS.md|CLAUDE.md)
    IS_GENERATED=1
    ;;
esac
if [[ "$REL_PATH" == .claude/rules/*.md ]]; then
  IS_GENERATED=1
elif [[ "$REL_PATH" == */AGENTS.md ]]; then
  IS_GENERATED=1
fi

if [ "$IS_GENERATED" -eq 1 ]; then
  SOURCE_HINT=""
  if [[ "$REL_PATH" =~ ^\.claude/rules/(.+)\.md$ ]]; then
    SOURCE_HINT="ai/rules/${BASH_REMATCH[1]}.md"
  elif [[ "$REL_PATH" =~ ^(.+)/AGENTS\.md$ ]]; then
    SOURCE_HINT="${BASH_REMATCH[1]}/CLAUDE.md"
  fi

  printf '%s is generated by bin/sync-agent-config.\n' "$REL_PATH" >&2
  if [ -n "$SOURCE_HINT" ]; then
    printf 'Edit %s instead. Sync runs automatically after source edits.\n' "$SOURCE_HINT" >&2
  else
    printf 'Edit ai/common/*.md or ai/rules/*.md instead. Sync runs automatically after source edits.\n' >&2
  fi
  exit 2
fi

IS_AGENT_CONFIG=0
if [[ "$REL_PATH" =~ ^ai/.*\.md$ ]]; then
  IS_AGENT_CONFIG=1
elif [[ "$REL_PATH" == */CLAUDE.md ]] && [[ "$REL_PATH" != .claude/* ]]; then
  IS_AGENT_CONFIG=1
fi

if [ "$IS_AGENT_CONFIG" -eq 1 ]; then
  SYNC_OUTPUT=$(cd "$PROJECT_DIR" && bin/sync-agent-config 2>&1)
  SYNC_STATUS=$?
  if [ "$SYNC_STATUS" -ne 0 ]; then
    printf 'sync-agent-config failed after edit to %s:\n%s\n' "$REL_PATH" "$SYNC_OUTPUT" >&2
    exit 2
  fi
fi

exit 0
