[env]
_.path = ["./bin"]
_.file = [".env", "worktree.env"]

[tools]
go = "1.26.4"
air = "1.65.3"
gofumpt = "0.10.0"
golangci-lint = "2.12.2"
shellcheck = "0.11.0"
"go:github.com/a-h/templ/cmd/templ" = "0.3.1020"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.3.0"
"go:github.com/jackc/tern/v2" = "2.4.1"
