// modelgen generates model structs and row maps from the live database
// schema. The schema is the source of truth: column types, nullability,
// defaults, and comments are introspected from Postgres, never
// hand-maintained, so the Go model cannot drift from the database.
//
// Reads modelgen.yaml, connects via PG env vars.
// Usage: go run ./cmd/modelgen
package main

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/jackc/pgx/v5"
	"golang.org/x/tools/imports"
	"gopkg.in/yaml.v3"
)

type Config struct {
	Tables []TableConfig `yaml:"tables"`
}

type TableConfig struct {
	Table   string `yaml:"table"`
	Package string `yaml:"package"`
	Type    string `yaml:"type"`
}

type column struct {
	Name       string
	UDT        string
	Nullable   bool
	HasDefault bool
	IsPK       bool
	Comment    string
}

func main() {
	ctx := context.Background()

	raw, err := os.ReadFile("modelgen.yaml")
	if err != nil {
		fatalf("reading config: %v", err)
	}

	var config Config
	if err := yaml.Unmarshal(raw, &config); err != nil {
		fatalf("parsing config: %v", err)
	}

	if len(config.Tables) == 0 {
		fmt.Println("modelgen: no tables configured in modelgen.yaml - nothing to generate")
		return
	}

	conn, err := pgx.Connect(ctx, "")
	if err != nil {
		fatalf("connecting (PG env vars): %v", err)
	}
	defer conn.Close(ctx)

	for _, table := range config.Tables {
		if err := generate(ctx, conn, table); err != nil {
			fatalf("generating %s: %v", table.Table, err)
		}
	}
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "modelgen: "+format+"\n", args...)
	os.Exit(1)
}

const columnsSQL = `
SELECT
  c.column_name,
  c.udt_name,
  c.is_nullable = 'YES',
  c.column_default IS NOT NULL,
  COALESCE(pk.is_pk, false),
  COALESCE(col_description(($1 || '.' || $2)::regclass, c.ordinal_position), '')
FROM information_schema.columns c
LEFT JOIN (
  SELECT a.attname AS column_name, true AS is_pk
  FROM pg_index i
  JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
  WHERE i.indrelid = ($1 || '.' || $2)::regclass AND i.indisprimary
) pk ON pk.column_name = c.column_name
WHERE c.table_schema = $1 AND c.table_name = $2
ORDER BY c.ordinal_position
`

func generate(ctx context.Context, conn *pgx.Conn, table TableConfig) error {
	rows, err := conn.Query(ctx, columnsSQL, "public", table.Table)
	if err != nil {
		return fmt.Errorf("introspecting: %w", err)
	}

	var columns []column

	var col column
	_, err = pgx.ForEachRow(rows, []any{&col.Name, &col.UDT, &col.Nullable, &col.HasDefault, &col.IsPK, &col.Comment}, func() error {
		columns = append(columns, col)
		return nil
	})
	if err != nil {
		return fmt.Errorf("scanning columns: %w", err)
	}

	if len(columns) == 0 {
		return fmt.Errorf("table %s has no columns (does it exist?)", table.Table)
	}

	src, err := render(table, columns)
	if err != nil {
		return err
	}

	path := filepath.Join(table.Package, "model_gen.go")

	out, err := imports.Process(path, src, nil)
	if err != nil {
		return fmt.Errorf("resolving imports: %w\n%s", err, src)
	}

	if err := os.WriteFile(path, out, 0o600); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

func render(table TableConfig, columns []column) ([]byte, error) {
	receiver := receiverName(table.Type)

	var b bytes.Buffer
	fmt.Fprintf(&b, "// Code generated by modelgen from table %q. DO NOT EDIT.\n\n", table.Table)
	fmt.Fprintf(&b, "package %s\n\n", table.Package)

	fmt.Fprintf(&b, "// %s is the row model for the %s table.\n", table.Type, table.Table)
	fmt.Fprintf(&b, "type %s struct {\n", table.Type)

	for _, col := range columns {
		goType, err := goType(col)
		if err != nil {
			return nil, err
		}

		if col.Comment != "" {
			fmt.Fprintf(&b, "\t// %s\n", col.Comment)
		}

		fmt.Fprintf(&b, "\t%s %s `db:%q`\n", fieldName(col.Name), goType, col.Name)
	}

	fmt.Fprintf(&b, "}\n\n")

	fmt.Fprintf(&b, "// ToRowMap returns the column map used to build inserts and updates.\n")
	fmt.Fprintf(&b, "// The primary key is omitted, and zero values are dropped for columns\n")
	fmt.Fprintf(&b, "// whose default lives in the database.\n")
	fmt.Fprintf(&b, "func (%s %s) ToRowMap() pgsql.RowMap {\n", receiver, table.Type)
	fmt.Fprintf(&b, "\trm := pgsql.RowMap{\n")

	var defaulted []string

	for _, col := range columns {
		if col.IsPK {
			continue
		}

		if col.HasDefault {
			defaulted = append(defaulted, fmt.Sprintf("%q", col.Name))
		}

		fmt.Fprintf(&b, "\t\t%q: %s.%s,\n", col.Name, receiver, fieldName(col.Name))
	}

	fmt.Fprintf(&b, "\t}\n")

	if len(defaulted) > 0 {
		fmt.Fprintf(&b, "\n\tdb.FilterUnset(rm, %s)\n", strings.Join(defaulted, ", "))
	}

	fmt.Fprintf(&b, "\n\treturn rm\n}\n")

	return b.Bytes(), nil
}

func goType(col column) (string, error) {
	if col.IsPK {
		switch col.UDT {
		case "int4", "int8":
			return "int64", nil
		}
	}

	// uuid and numeric map to string deliberately: no forced uuid
	// dependency, and no float corruption for arbitrary-precision values.
	// Projects that adopt a uuid or decimal package change two lines here.
	base, ok := map[string]string{
		"int2":        "int",
		"int4":        "int",
		"int8":        "int64",
		"varchar":     "string",
		"text":        "string",
		"bool":        "bool",
		"float4":      "float64",
		"float8":      "float64",
		"timestamp":   "time.Time",
		"timestamptz": "time.Time",
		"jsonb":       "[]byte",
		"_varchar":    "[]string",
		"_text":       "[]string",
		"_int4":       "[]int",
		"_int8":       "[]int64",
		"uuid":        "string",
		"citext":      "string",
		"date":        "time.Time",
		"bytea":       "[]byte",
		"numeric":     "string",
	}[col.UDT]

	if !ok {
		return "", fmt.Errorf("column %s: no Go mapping for Postgres type %q — add one to modelgen", col.Name, col.UDT)
	}

	if col.Nullable && !strings.HasPrefix(base, "[]") {
		return "*" + base, nil
	}

	return base, nil
}

// fieldName converts a snake_case column to an exported Go name,
// uppercasing initialisms like id.
func fieldName(column string) string {
	parts := strings.Split(column, "_")

	for i, part := range parts {
		if part == "id" {
			parts[i] = "ID"
			continue
		}

		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}

	return strings.Join(parts, "")
}

// receiverName avoids shadowing the imports the generated file needs.
func receiverName(typeName string) string {
	name := strings.ToLower(typeName)

	switch name {
	case "db", "pgsql", "time":
		return "m"
	}

	return name
}
