// Code generated by conngen. DO NOT EDIT.

// Direct db.Conn variants of this package's *Tx functions.

package auth

import (
	"context"

	"github.com/mbriggs/go-bootstrap/db"
)

// Authenticate is the direct db.Conn variant of AuthenticateTx.
func Authenticate(ctx context.Context, email, password string) (User, error) {
	return AuthenticateTx(ctx, db.Conn, email, password)
}

// ByEmail is the direct db.Conn variant of ByEmailTx.
func ByEmail(ctx context.Context, email string) (User, error) {
	return ByEmailTx(ctx, db.Conn, email)
}

// ByID is the direct db.Conn variant of ByIDTx.
func ByID(ctx context.Context, id int64) (User, error) {
	return ByIDTx(ctx, db.Conn, id)
}

// Create is the direct db.Conn variant of CreateTx.
func Create(ctx context.Context, in CreateInput) (User, error) {
	return CreateTx(ctx, db.Conn, in)
}
