// Code generated by txgen. DO NOT EDIT.

package auth

import (
	"context"

	"github.com/mbriggs/go-bootstrap/db"
)

// Authenticate delegates to AuthenticateTx using the connection pool.
func Authenticate(ctx context.Context, email, password string) (User, error) {
	return AuthenticateTx(ctx, db.Conn, email, password)
}

// ByEmail delegates to ByEmailTx using the connection pool.
func ByEmail(ctx context.Context, email string) (User, error) {
	return ByEmailTx(ctx, db.Conn, email)
}

// ByID delegates to ByIDTx using the connection pool.
func ByID(ctx context.Context, id int64) (User, error) {
	return ByIDTx(ctx, db.Conn, id)
}

// Create delegates to CreateTx using the connection pool.
func Create(ctx context.Context, in CreateInput) (User, error) {
	return CreateTx(ctx, db.Conn, in)
}
