// Code generated by modelgen from table "users". DO NOT EDIT.

package auth

import (
	"time"

	"github.com/mbriggs/go-bootstrap/db"
	"github.com/mbriggs/pgsql"
)

// User is the row model for the users table.
type User struct {
	ID           int64     `db:"id"`
	Email        string    `db:"email"`
	PasswordHash string    `db:"password_hash"`
	Name         string    `db:"name"`
	Roles        []string  `db:"roles"`
	CreatedAt    time.Time `db:"created_at"`
	UpdatedAt    time.Time `db:"updated_at"`
}

// ToRowMap returns the column map used to build inserts and updates.
// The primary key is omitted, and zero values are dropped for columns
// whose default lives in the database.
func (user User) ToRowMap() pgsql.RowMap {
	rm := pgsql.RowMap{
		"email":         user.Email,
		"password_hash": user.PasswordHash,
		"name":          user.Name,
		"roles":         user.Roles,
		"created_at":    user.CreatedAt,
		"updated_at":    user.UpdatedAt,
	}

	db.FilterUnset(rm, "name", "roles", "created_at", "updated_at")

	return rm
}
