// Code generated by modelgen from table "password_reset_tokens". DO NOT EDIT.

package auth

import (
	"time"

	"github.com/mbriggs/go-bootstrap/db"
	"github.com/mbriggs/pgsql"
)

// PasswordResetToken is the row model for the password_reset_tokens table.
type PasswordResetToken struct {
	ID        int64      `db:"id"`
	UserID    int64      `db:"user_id"`
	TokenHash string     `db:"token_hash"`
	ExpiresAt time.Time  `db:"expires_at"`
	UsedAt    *time.Time `db:"used_at"`
	CreatedAt time.Time  `db:"created_at"`
}

// ToRowMap returns the column map used to build inserts and updates.
// The primary key is omitted, and zero values are dropped for columns
// whose default lives in the database.
func (passwordresettoken PasswordResetToken) ToRowMap() pgsql.RowMap {
	rm := pgsql.RowMap{
		"user_id":    passwordresettoken.UserID,
		"token_hash": passwordresettoken.TokenHash,
		"expires_at": passwordresettoken.ExpiresAt,
		"used_at":    passwordresettoken.UsedAt,
		"created_at": passwordresettoken.CreatedAt,
	}

	db.FilterUnset(rm, "created_at")

	return rm
}
