// txgen generates the bare, pool-backed delegate for every hand-written
// transaction-composable function. The convention: persistence functions are
// hand-written only in their FooTx(ctx, tx db.Queryable, ...) form; the bare
// Foo form that supplies db.Conn is emitted here, so hand-written code never
// references the pool mid-call-tree and the delegate cannot drift.
//
// Usage: go run ./cmd/txgen ./db ./docindex
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/imports"
)

const genFileName = "delegates_gen.go"

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: txgen <package patterns>")
		os.Exit(1)
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedCompiledGoFiles,
	}

	pkgs, err := packages.Load(cfg, os.Args[1:]...)
	if err != nil {
		fatal("loading packages: %v", err)
	}

	if packages.PrintErrors(pkgs) > 0 {
		os.Exit(1)
	}

	for _, pkg := range pkgs {
		if len(pkg.CompiledGoFiles) == 0 {
			continue
		}

		if err := generate(pkg); err != nil {
			fatal("generating for %s: %v", pkg.PkgPath, err)
		}
	}
}

func fatal(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "txgen: "+format+"\n", args...)
	os.Exit(1)
}

type delegate struct {
	name string
	src  string
}

func generate(pkg *packages.Package) error {
	var delegates []delegate

	for i, file := range pkg.Syntax {
		filename := pkg.CompiledGoFiles[i]
		if filepath.Base(filename) == genFileName {
			continue
		}

		for _, decl := range file.Decls {
			fn, ok := decl.(*ast.FuncDecl)
			if !ok || fn.Recv != nil || !fn.Name.IsExported() {
				continue
			}

			if !strings.HasSuffix(fn.Name.Name, "Tx") {
				continue
			}

			txField := queryableField(pkg, fn)
			if txField == -1 {
				continue
			}

			src, err := render(pkg, fn, txField)
			if err != nil {
				return fmt.Errorf("rendering %s: %w", fn.Name.Name, err)
			}

			delegates = append(delegates, delegate{name: fn.Name.Name, src: src})
		}
	}

	dir := dirOf(pkg)

	if len(delegates) == 0 {
		return removeStale(dir)
	}

	sort.Slice(delegates, func(i, j int) bool { return delegates[i].name < delegates[j].name })

	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by txgen. DO NOT EDIT.\n\npackage %s\n\n", pkg.Name)

	for _, d := range delegates {
		buf.WriteString(d.src)
		buf.WriteString("\n")
	}

	path := filepath.Join(dir, genFileName)

	out, err := imports.Process(path, buf.Bytes(), nil)
	if err != nil {
		return fmt.Errorf("resolving imports (%s): %w\n%s", path, err, buf.String())
	}

	return os.WriteFile(path, out, 0o644)
}

func dirOf(pkg *packages.Package) string {
	return filepath.Dir(pkg.CompiledGoFiles[0])
}

func removeStale(dir string) error {
	path := filepath.Join(dir, genFileName)

	err := os.Remove(path)
	if os.IsNotExist(err) {
		return nil
	}

	return err
}

// queryableField returns the index of the db.Queryable parameter field,
// or -1 when the function does not follow the delegate convention.
func queryableField(pkg *packages.Package, fn *ast.FuncDecl) int {
	for i, field := range fn.Type.Params.List {
		t := pkg.TypesInfo.TypeOf(field.Type)
		if t == nil {
			continue
		}

		if strings.HasSuffix(t.String(), "db.Queryable") || t.String() == "Queryable" {
			if len(field.Names) != 1 {
				return -1
			}

			return i
		}
	}

	return -1
}

func render(pkg *packages.Package, fn *ast.FuncDecl, txField int) (string, error) {
	bare := strings.TrimSuffix(fn.Name.Name, "Tx")

	if alreadyDefined(pkg, bare) {
		return "", fmt.Errorf("%s already hand-written; delete it so txgen can own it", bare)
	}

	params, err := printFields(pkg.Fset, fn.Type.Params.List, txField)
	if err != nil {
		return "", err
	}

	results, err := printResults(pkg.Fset, fn.Type.Results)
	if err != nil {
		return "", err
	}

	typeParams, typeArgs, err := printTypeParams(pkg.Fset, fn.Type.TypeParams)
	if err != nil {
		return "", err
	}

	args := callArgs(fn, txField, connExpr(pkg))

	var b strings.Builder
	fmt.Fprintf(&b, "// %s delegates to %s using the connection pool.\n", bare, fn.Name.Name)
	fmt.Fprintf(&b, "func %s%s(%s)%s {\n", bare, typeParams, params, results)
	fmt.Fprintf(&b, "\treturn %s%s(%s)\n}\n", fn.Name.Name, typeArgs, strings.Join(args, ", "))

	return b.String(), nil
}

func alreadyDefined(pkg *packages.Package, name string) bool {
	obj := pkg.Types.Scope().Lookup(name)
	if obj == nil {
		return false
	}

	return filepath.Base(pkg.Fset.Position(obj.Pos()).Filename) != genFileName
}

// connExpr is unqualified inside the package that declares the pool.
func connExpr(pkg *packages.Package) string {
	if obj := pkg.Types.Scope().Lookup("Conn"); obj != nil {
		return "Conn"
	}

	return "db.Conn"
}

func printFields(fset *token.FileSet, fields []*ast.Field, skip int) (string, error) {
	var parts []string

	for i, field := range fields {
		if i == skip {
			continue
		}

		typeStr, err := printExpr(fset, field.Type)
		if err != nil {
			return "", err
		}

		names := make([]string, len(field.Names))
		for j, n := range field.Names {
			names[j] = n.Name
		}

		parts = append(parts, strings.Join(names, ", ")+" "+typeStr)
	}

	return strings.Join(parts, ", "), nil
}

func printResults(fset *token.FileSet, results *ast.FieldList) (string, error) {
	if results == nil || len(results.List) == 0 {
		return "", nil
	}

	var parts []string

	for _, field := range results.List {
		typeStr, err := printExpr(fset, field.Type)
		if err != nil {
			return "", err
		}

		for range max(len(field.Names), 1) {
			parts = append(parts, typeStr)
		}
	}

	if len(parts) == 1 {
		return " " + parts[0], nil
	}

	return " (" + strings.Join(parts, ", ") + ")", nil
}

func printTypeParams(fset *token.FileSet, tparams *ast.FieldList) (decl string, args string, err error) {
	if tparams == nil || len(tparams.List) == 0 {
		return "", "", nil
	}

	var declParts, argParts []string

	for _, field := range tparams.List {
		constraint, err := printExpr(fset, field.Type)
		if err != nil {
			return "", "", err
		}

		names := make([]string, len(field.Names))
		for i, n := range field.Names {
			names[i] = n.Name
		}

		declParts = append(declParts, strings.Join(names, ", ")+" "+constraint)
		argParts = append(argParts, names...)
	}

	return "[" + strings.Join(declParts, ", ") + "]", "[" + strings.Join(argParts, ", ") + "]", nil
}

func callArgs(fn *ast.FuncDecl, txField int, conn string) []string {
	var args []string

	for i, field := range fn.Type.Params.List {
		if i == txField {
			args = append(args, conn)
			continue
		}

		_, variadic := field.Type.(*ast.Ellipsis)

		for _, n := range field.Names {
			arg := n.Name
			if variadic {
				arg += "..."
			}

			args = append(args, arg)
		}
	}

	return args
}

func printExpr(fset *token.FileSet, expr ast.Expr) (string, error) {
	var buf bytes.Buffer

	if err := printer.Fprint(&buf, fset, expr); err != nil {
		return "", err
	}

	return buf.String(), nil
}
