// Code generated by conngen. DO NOT EDIT.

// Direct db.Conn variants of this package's *Tx functions.

package db

import (
	"context"

	"github.com/mbriggs/pgsql"
)

// Delete is the direct db.Conn variant of DeleteTx.
func Delete(ctx context.Context, del *pgsql.DeleteStatement) (int64, error) {
	return DeleteTx(ctx, Conn, del)
}

// FindAll is the direct db.Conn variant of FindAllTx.
func FindAll[T any](ctx context.Context, sql string, args ...any) ([]T, error) {
	return FindAllTx[T](ctx, Conn, sql, args...)
}

// FindExactlyOne is the direct db.Conn variant of FindExactlyOneTx.
func FindExactlyOne[T any](ctx context.Context, sql string, args ...any) (T, error) {
	return FindExactlyOneTx[T](ctx, Conn, sql, args...)
}

// FindOne is the direct db.Conn variant of FindOneTx.
func FindOne[T any](ctx context.Context, sql string, args ...any) (T, error) {
	return FindOneTx[T](ctx, Conn, sql, args...)
}

// Insert is the direct db.Conn variant of InsertTx.
func Insert[T any](ctx context.Context, insert *pgsql.InsertStatement) (T, error) {
	return InsertTx[T](ctx, Conn, insert)
}

// Update is the direct db.Conn variant of UpdateTx.
func Update(ctx context.Context, update *pgsql.UpdateStatement) (int64, error) {
	return UpdateTx(ctx, Conn, update)
}
