// Code generated by txgen. DO NOT EDIT.

package db

import (
	"context"

	"github.com/mbriggs/pgsql"
)

// FindAll delegates to FindAllTx using the connection pool.
func FindAll[T any](ctx context.Context, sql string, args ...any) ([]T, error) {
	return FindAllTx[T](ctx, Conn, sql, args...)
}

// Find delegates to FindTx using the connection pool.
func Find[T any](ctx context.Context, sql string, args ...any) (T, error) {
	return FindTx[T](ctx, Conn, sql, args...)
}

// Update delegates to UpdateTx using the connection pool.
func Update(ctx context.Context, update *pgsql.UpdateStatement) (int64, error) {
	return UpdateTx(ctx, Conn, update)
}
