// Code generated by conngen. DO NOT EDIT.

// Direct db.Conn variants of this package's *Tx functions.

package web

import (
	"context"

	"github.com/mbriggs/go-bootstrap/db"
)

// ThrottleBlocked is the direct db.Conn variant of ThrottleBlockedTx.
func ThrottleBlocked(ctx context.Context, key string) (bool, error) {
	return ThrottleBlockedTx(ctx, db.Conn, key)
}

// ThrottleFail is the direct db.Conn variant of ThrottleFailTx.
func ThrottleFail(ctx context.Context, key string) error {
	return ThrottleFailTx(ctx, db.Conn, key)
}

// ThrottleReset is the direct db.Conn variant of ThrottleResetTx.
func ThrottleReset(ctx context.Context, key string) error {
	return ThrottleResetTx(ctx, db.Conn, key)
}
